# vim:ts=2:sw=2:et

# It seems that ImageMagick (the system package) is required in version 6.8 or above.
# ImageMagick 6.7 doesn't have everything we need (PHP Fatal error:  Undefined class constant 'ALPHACHANNEL_REMOVE').

dist: xenial

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.3
  - 7.4snapshot

before_install:
  - sudo apt-get install pngquant
  - sudo apt-get install imagemagick
  - printf "\n" | pecl install imagick
  - php -i
  - composer update --dev

script:
  - cd test && ../vendor/bin/run_unit_tests && echo "Everything looks good"
