# vim:ts=2:sw=2:et

os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

dist: focal

language: php

jobs:
  include:
    - php: 7.4
      dist: focal
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal
    - name: "PHP: 8.2"
      dist: jammy
      language: ruby # This makes no sence to me, but it works!
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.2 php8.2-gd php8.2-imagick 2>&1
        - sudo apt-get install pngquant 2>&1
        - sudo apt install libonig5
        - php -v
      before_script:
        - php -i
        - composer update --dev --ignore-platform-req=ext-imagick 2>&1
    - name: "PHP: 8.3"
      dist: jammy
      language: ruby # This makes no sence to me, but it works!
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.3 php8.3-gd php8.3-imagick 2>&1
        - sudo apt-get install pngquant 2>&1
        - sudo apt install libonig5
        - php -v
      before_script:
        - php -i
        - composer update --dev --ignore-platform-req=ext-imagick 2>&1

before_install:
  - sudo apt-get update
  - sudo apt-get install pngquant libmagickwand-dev php-pear
  - echo | sudo pecl install imagick
  - echo 'extension=imagick.so' | sudo tee --append `php --ini | grep 'Loaded Configuration File' | sed 's/^.*:\s*//'` > /dev/null

before_script:
  - php -i
  - composer update --dev 2>&1

script:
  - cd test && ../vendor/bin/run_unit_tests && echo "Everything looks good"
