# vim:ts=2:sw=2:et

os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

dist: hirsute

language: php

php:
  - 7.4
  - 8.0
  - 8.1

before_install:
  - sudo apt-get update
  - sudo apt-get install pngquant libmagickwand-dev libheif-dev php-pear
  - echo | sudo pecl install imagick
  - echo 'extension=imagick.so' | sudo tee --append `php --ini | grep 'Loaded Configuration File' | sed 's/^.*:\s*//'` > /dev/null
  - php -i
  - composer update --dev

script:
  - cd test && ../vendor/bin/run_unit_tests && echo "Everything looks good"
